### ISSUE TITLE
Test Implementation of Reading / Writing / Spawning

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/carla-interface#7]
Reading World from Carla
Spawning an agent
Writing Control Commands (i.e. high acceleration)

Outcome: Python script, we can then observe the inputs commands play out in the Carla world

**Comment by klemense1** [comment]
findings from Carla's documentation: the synchronous mode with fixed_time_step only works above 10 Hz (see documentation)
--> try to unit test wether synchronous mode really works above 10Hz
- try to read the world data between two ticks and assert that they are equal

**Comment by klemense1** [comment]
Question about weather: Does it affect anything of our "semantic simulation", i.e. traction of our vehicle? impact to sensors has no value for us.

**Comment by tin1254** [comment]
> Question about weather: Does it affect anything of our "semantic simulation", i.e. traction of our vehicle? impact to sensors has no value for us.

It has no impact on the vehicle control, but only to sensors like camera
https://github.com/carla-simulator/carla/issues/655

**Comment by tin1254** [comment]
> findings from Carla's documentation: the synchronous mode with fixed_time_step only works above 10 Hz (see documentation)
> --> try to unit test wether synchronous mode really works above 10Hz
> 
>     * try to read the world data between two ticks and assert that they are equal

According to [this merge of Carla](https://github.com/carla-simulator/carla/pull/1803) and the results of my test case:

- the physical behavior becomes abnormal (half the velocity if 5Hz) if it is <10Hz. On the other hand, if it is >60Hz, weird physical movement is observed occasionally (however the velocity is normal). If 10<x<60, everything is fine by my observation.
- After calling tick() in a client, the client's thread halts/is blocked until the tick is finished which means after calling tick, the simulator will halt since 0.9.6 (i.e. wait_for_tick() is implemented inside tick()). That means the data between two tick() is always the same

Also I misunderstood the fixed time-step last time, the smaller the time-step, the more realistic the physical simulation it will be, at the same time the simulation will run slower (simulation time-step will be slower than real-time), and vice verse.
